#!/bin/sh

# key bindings
sxhkd &

# notificatoins manager
dunst &

# bar
~/.config/polybar/docky/launch.sh &

# compositor
picom --experimental-backends -b

# set layouts
setxkbmap -layout us,ar -option "grp:alt_shift_toggle"

# red light shifter
redshift-gtk -l manual -l 55:37 &

# swallow
pgrep bspswallow || ~/.local/scripts/bspswallow &

# screenshot app
flameshot &

# autolock within 10 minutes
xautolock -detectsleep              \
          -time 15                  \
          -locker "i3lock-fancy"    \
          -notify 30                \
          -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" & 

# power manager
mate-power-manager &

# network apps
blueman-applet &
blueman-tray &
nm-applet &

# udisk manager
udiskie -t &

# conky
~/.config/conky/launch.sh

# optimus manager
#optimus-manager-qt

# Fix java grey blobs
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
wmname LG3D

# Monitors
#configure_monitors
