#!/bin/sh

# env
export XDG_CURRENT_DESKTOP=bspwm
export XDG_SESSION_TYPE=X11

# clipmenud opts
export CM_SELECTIONS="clipboard"
export CM_LAUNCHER="rofi"

# load saved theme & wallpaper
wal -Rst 2>&1 >/dev/null

#############   configuration   ###############
bspc config window_gap                 8
bspc config split_ratio                0.50
bspc config gapless_monocle            false

bspc config top_padding                45
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config paddingless_monocle        true

bspc config click_to_focus             false
bspc config single_monocle             true
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config ignore_ewmh_focus          true
bspc config history_aware_focus        true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc config pointer_follows_monitor    true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner

bspc config border_width               2
bspc config borderless_monocle         true
bspc config focused_border_color       "$(xrdb -g color1)"
bspc config presel_feedback_color      "$(xrdb -g color3)"

# floating apps
export FLOATING="feh mpv flameshot PCSX2 *:SPLASH"

for app in $FLOATING; do
    bspc rule -a "$app" state='floating'
done

# default desktop for apps
bspc rule -a 'Chromium' -o desktop=3
bspc rule -a 'Telegram' -o desktop=8

#############    desktops   ###############
update_monitors() {
  set -- $(bspc query -M)

  if [ $# -eq 2 ]; then
    bspc monitor "$1" -d 1 3 5 7
    bspc monitor "$2" -d 2 4 6 8
  else
    bspc monitor -d 1 2 3 4 5 6 7 8
  fi
}

# initial setup
update_monitors

# update on monitor add/remove
once bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_remove*) update_monitors;;
  esac
done &

#############   autostart   ###############

# session
once lxsession -e BSPWM -a &
once gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh &

# keyboard
setxkbmap -layout us,ara -option "grp:win_space_toggle"
xinput set-prop 13 339 1
xinput set-prop 13 341 1
xinput set-prop 13 347 1
xinput set-prop 13 349 1

# key bindings
once sxhkd &

# audio
once -f pipewire &
once -f pipewire-pulse &
once -f wireplumber &

# font
xset +fp $HOME/.local/share/fonts
xset fp rehash

# autolock
xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- "$HOME/.config/bspwm/scripts/dimmer" &

# apps
once picom -b                                      # compositor
once clipmenud &                                   # clipboard manager
once dunst &                                       # notifications daemon
once -n polybar $HOME/.config/polybar/launch.sh &  # top-bar
once nm-applet &                                   # mounting util
once udiskie &                                     # mounting util
once -n redshift redshift-gtk &                    # reduced blue-light indicator
once easyeffects --gapplication-service -q &       # audio effects

#############   finialization   ###############

# update dbus vars
dbus-update-activation-environment --all

# vim: ft=bash
