#!/bin/sh

# kvantum theme
export QT_STYLE_OVERRIDE=kvantum

# clipmenud opts
export CM_SELECTIONS="clipboard"
export CM_LAUNCHER="rofi"

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
export JDK_JAVA_OPTIONS="\
	-Dawt.useSystemAAFontSettings=on \
	-Dswing.aatext=true \
	-Djdk.gtk.version=3 \
	-Dsun.java2d.opengl=true \
	-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel \
	-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"

# style
export QT_STYLE_OVERRIDE=kvantum

#############   configuration   ###############
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config gapless_monocle false

bspc config top_padding 45
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config paddingless_monocle true

bspc config click_to_focus false
bspc config single_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width 2
bspc config borderless_monocle true
bspc config focused_border_color "$(xrdb -g color1)"
bspc config presel_feedback_color "$(xrdb -g color3)"

# rules
bspc rule -a 'Chromium' -o desktop=3 follow=on
bspc rule -a 'Telegram' desktop=8
bspc rule -a 'flameshot' state='floating'
bspc rule -a 'PCSX2' state='floating'
bspc rule -a '*:SPLASH' state='floating'
bspc rule -a 'mpv' state='floating'
bspc rule -a 'Sloaar' state='floating'
bspc rule -a 'nm-connection-editor' state='floating'

#############    desktops   ###############
update_monitors() {
	# shellcheck disable=SC2046
	set -- $(bspc query -M)
	last_desktop="$(bspc query -d focused -D --names)"

	if [ $# -eq 2 ]; then
		bspc monitor "$1" -d 1 3 5 7
		bspc monitor "$2" -d 2 4 6 8
	else
		bspc monitor -d 1 2 3 4 5 6 7 8
	fi

	if [ -n "$last_desktop" ]; then
		bspc desktop -f "$last_desktop"
	fi
}

# initial setup
update_monitors

# update on monitor add/remove
bspc subscribe monitor | while read -r line; do
	case $line in
	monitor_add* | monitor_remove*)
		update_monitors
		;;
	esac
done &

#############   autostart   ###############

# session
once -w lxsession -e BSPWM -a &

# key bindings
once -w sxhkd &

# audio
once -w -f pipewire &

# screen lock
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- "$XDG_CONFIG_HOME/bspwm/scripts/dimmer" &

# apps
once -w picom -b                                          # compositor
once -w batsignal -epb -a "System Power"                  # battery notifications
once -w clipmenud &                                       # clipboard manager
once -w dunst &                                           # notifications daemon
once -w -n polybar "$XDG_CONFIG_HOME/polybar/launch.sh" & # top-bar
once -w nm-applet &                                       # mounting util
once -w udiskie &                                         # mounting util
once -w -n redshift redshift-gtk &                        # reduced blue-light indicator
once -w easyeffects --gapplication-service -q &           # audio effects

#############   finialization   ###############

# update dbus vars
dbus-update-activation-environment --all

# vim: ft=bash
